### ISSUE TITLE
Exception raised on server shutdown

### ISSUE THREAD

**Issue by dlqqq** [jupyter-ai-contrib/jupyter-ai-persona-manager#5]
## Description

This bug was introduced by #3:

```
[E 2025-10-14 10:47:06.684 PersonaManagerExtension] Persona Manager extension raised an exception while stopping:
[E 2025-10-14 10:47:06.684 PersonaManagerExtension] 'PersonaManagerExtension' object has no attribute 'persona_managers_by_room'
    Traceback (most recent call last):
      File "/Users/dlq/micromamba/envs/jai3n/lib/python3.13/site-packages/jupyter_ai_persona_manager/extension.py", line 181, in stop_extension
        await self._stop_extension()
      File "/Users/dlq/micromamba/envs/jai3n/lib/python3.13/site-packages/jupyter_ai_persona_manager/extension.py", line 192, in _stop_extension
        for room_id, persona_manager in self.persona_managers_by_room.items():
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'PersonaManagerExtension' object has no attribute 'persona_managers_by_room'. Did you mean: 'persona_manager_class'?
```
